name: PHP package

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - staging
      - develop

jobs:
  code-convention:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-version }}
        tools: php-cs-fixer, phpunit, phpcs, phpcbf
    - name: Testing with php-cs-fixer
      run: |
        # go to php folder
        cd php
        # run php-cs-fixer
        php-cs-fixer fix --dry-run
        phpcs .
        phpcbf .
  
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/develop'
    needs: code-convention
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: |
          echo "Build Package!"

  deploy:
    runs-on: ubuntu-latest
    needs: [code-convention, build]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy
        run: |
          echo "Deploy Package!"