name: Python package

on:
  push:
    branches:
      - master
      - staging
      - develop
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - staging
      - develop

jobs:
  deploy-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy api to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_PUB_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            whoami
            cd backend
            git status