name: Python package

on:
  push:
    branches:
      - master
      - staging
      - develop
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - staging
      - develop
env:
  setup-ssh-server: |
    sudo apt update && sudo apt install openssh-server sudo -y 
  set-ssh-key: |
    mkdir -p ~/.ssh/
    echo ${{secrets.DROPLET_PRIVATE_KEY}} > ~/.ssh/id_rsa
    sudo chmod 600 ~/.ssh/id_rsa

jobs:
  deploy-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy api to DigitalOcean Droplet
        run: |
          # ${{env.setup-ssh-server}}
          # ${{env.set-ssh-key}}
          sudo apt update && sudo apt install openssh-server sudo -y 
          mkdir -p ~/.ssh/
          echo ${{secrets.DROPLET_PRIVATE_KEY}} > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh root@${{secrets.DROPLET_PUB_IP}}
          ls -la